image: alpine/latest
triggers:
  - action: email
    condition: failure
    to: "<pe@pan.earth>"
secrets:
- cc1a3890-4696-48f6-bc12-f73d87dd0f20
sources:
- https://git.sr.ht/~bakpakin/janet#v1.40.1
- https://github.com/janet-lang/spork.git
- https://github.com/janet-lang/jhydro.git
- git@git.sr.ht:~pepe/gp
- git@git.sr.ht:~pepe/interstudy
tasks:
  - janet: |
        cd janet
        make -j
        sudo make install
  - interstudy-test: |
        cd interstudy
        sudo janet --install ../spork
        sudo janet --install ../jhydro
        sudo janet --install ../gp
        CONF=test/conf.test.jdn /usr/local/lib/janet/bin/janet-pm test
